### ISSUE TITLE
Cannot read properties error

### ISSUE THREAD

**Issue by DomiKoch** [trustedshops-public/connect-app-connector#35]
### What happened?

Hi @Mhera17 ,

we have an error on QA Stage only, on the shopsystem Shopify only:

![image](https://github.com/trustedshops-public/connect-app-connector/assets/97980151/7096de56-1271-41d0-87fe-80c6f2e30318)

Before pushing the dark trustbadge change to prod, we want to identify, what causes this error. Our developer of baselayer couldnt find the root cause and mentions that the connector triggers this error. Could you investigate this error? Where does it come from?

### Problem description

The error occurs when you entry the plugin and stays inside the plugin environment.

### Expected behaviour

No errors while using the plugin.

### Actual  behaviour

No functionality problems.

### Steps to Reproduce

Just click into the app - Test Easy Integration on instance https://admin.shopify.com/store/easy-integration-test-2

open console

### I read and aggree to the contribution guidelines

- [X] I read and aggree to the contribution guidelines

**Comment by Mhera17** [comment]
Hi @DomiKoch. I will check and let you know

**Comment by Mhera17** [comment]
hi @DomiKoch. does this bug appear after our last changes(darkmode)?

**Comment by Mhera17** [comment]
it's strange, but in some cases there is no error.

<img width="1422" alt="Screenshot 2023-07-13 at 21 39 29" src="https://github.com/trustedshops-public/connect-app-connector/assets/130062707/e0afbb21-7ea7-419d-83c1-f5362fba35af">

I built a connector and added a .umd file to the demo app. There are no errors like inside Shopify.

<img width="947" alt="Screenshot 2023-07-14 at 01 00 45" src="https://github.com/trustedshops-public/connect-app-connector/assets/130062707/b905cd05-a524-45a4-b322-f5e771a13854">

**Comment by DomiKoch** [comment]
HI @Mhera17 ,

unfortunately we cant really say for sure it is after merging of darkmode. It could be occur before, we havent tested QA for a longer period of time. 

Its curious that its only appearing in Shopify. Does it make sense to roll back the darkmode change and look, whether the error still occurs?

Greetings

**Comment by Mhera17** [comment]
Hi @DomiKoch , 
Yes, I think it's a good idea to roll back the darkmode.
if it's not because of the dark mode, it will be more challenging. Then I'll go through the poll requests to understand what the problem might be.

Greetings

**Comment by Mhera17** [comment]
do I need to revert that PR from Github?

**Comment by DomiKoch** [comment]
Yeah would be nice!

Greetings

**Comment by Mhera17** [comment]
done

**Comment by DomiKoch** [comment]
HI @Mhera17 ,

error still appears. But on Prod it does not appear. The last Update on Prod was June 9th. 
It could be only from one of the changes inbetween June 9th to today or it is something in the App setup in SHopify.

Greetings

**Comment by Mhera17** [comment]
ok, i will check all changes from June 9th. 

Yesterday I did some research. I read in a couple of blogs that this could be because of the environment that the plugin is running (Shopify). hope this is not the same case

**Comment by Mhera17** [comment]
i guess this change includes June 9th update, right? 
https://github.com/trustedshops-public/connect-app-connector/pull/22

if yes, then only this change remains. https://github.com/trustedshops-public/connect-app-connector/pull/28
but I guess there is no change that could cause the error.
 but to be sure, we can revert that as well.

**Comment by DomiKoch** [comment]
Hi @Mhera17 ,

https://github.com/trustedshops-public/connect-app-connector/pull/28 seems to cause the errors.

Now they disappeared.

Greetings

**Comment by DomiKoch** [comment]
Wrong... They appeared now after some time... I will discuss with @eburck

**Comment by eburck** [comment]
still happens with Shopify (latest test build of connector):
![image](https://github.com/trustedshops-public/connect-app-connector/assets/5467488/6584b20a-0c76-4c49-99a8-5ea3fd99e123)

**Comment by Mhera17** [comment]
If I'm not mistaken, we reverted all the PRs to understand after which PR we got this error, but it didn't help.  
but sure, I'll check again

**Comment by Mhera17** [comment]
I'm not sure if the problem is with the connector. 
Just in case. Is it okay that our console logs show the same thing so many times and in the network we have doubled API calls?

<img width="1084" alt="Screenshot 2023-11-14 at 16 51 53" src="https://github.com/trustedshops-public/connect-app-connector/assets/130062707/4281fa02-514e-488b-ab0b-f2b82dc5327f">

**Comment by eburck** [comment]
Hm, indeed it looks like the app is initializing connector and eventslib multiple times with one request to the app page. Can this be responsible for the errors?

**Comment by Mhera17** [comment]
I think so. I think it makes sense to start by looking at Shopify's configuration. What do you think about it?
